### ISSUE TITLE
Rajouter l'attribut obligatoire label

### ISSUE THREAD

**Issue by MarcillaudG** [FlorentMouysset/Links2-javadriver#4]

**Comment by FlorentMouysset** [comment]
L'attribut "label" n'est pas obligatoire.
De plus, il est plus "générique" (pas seulement de l'affichage), son nom est "name".
Il est préférable d'utiliser la constante Entity.ATTRIBUTE_NAME.

Méthode : 
`setAttribute(String attributeName, Object attributeValue)`

Exemple d'utilisation :
`entity.setAttribute(Entity.ATTRIBUTE_NAME, "my_entity_name");`
